ATTACK_CATEGORIES = [
    "TOOL_POISONING",
    "INDIRECT_PROMPT_INJECTION",
    "UNSAFE_PERMISSIONS",
    "DATA_EXFILTRATION_PATTERN",
    "TASK_DRIFT",
]

SEVERITIES = ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]
